title: 'eLearn at PSCC'
author:
  name: 'Josh Dean'
  email: jmdean1@pstcc.edu
taxonomies:
  - category
  - tag
metadata:
  description: 'RTFM Skeleton'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
